### ISSUE TITLE
Currently does not compile on Ubuntu 13.10

### ISSUE THREAD

**Issue by jeffjshi** [macroevolution/bamm#23]
Haven't had a chance to try it on 13.9 but it appears the current (as of ~2 PM) version of the code no longer makes on my Linux machine. Yesterday afternoon's was fine. Error messages and log as follows:

enteril@Noctilio:~/Documents/Noctilio/Programs/bamm$ make
cd src && make bamm
make[1]: Entering directory `/home/enteril/Documents/Noctilio/Programs/bamm/src'
g++ -Wall -c -m64 -O3 -funroll-loops -g -DGIT_COMMIT_ID=\"43b1786793366b9be0d9df0776ddf84dae5b70cb\" main.cpp
main.cpp: In function ‘void exitWithMessageUsage()’:
main.cpp:170:5: error: ‘exit’ is not a member of ‘std’
     std::exit(0);
     ^
main.cpp:170:5: note: suggested alternative:
In file included from MCMC.h:12:0,
                 from main.cpp:10:
/usr/include/stdlib.h:542:13: note:   ‘exit’
 extern void exit (int __status) __THROW __attribute__ ((__noreturn__));
             ^
main.cpp: In function ‘void exitWithErrorUnknownArgument(const string&)’:
main.cpp:177:5: error: ‘exit’ is not a member of ‘std’
     std::exit(1);
     ^
main.cpp:177:5: note: suggested alternative:
In file included from MCMC.h:12:0,
                 from main.cpp:10:
/usr/include/stdlib.h:542:13: note:   ‘exit’
 extern void exit (int __status) __THROW __attribute__ ((__noreturn__));
             ^
main.cpp: In function ‘void exitWithErrorNoControlFile()’:
main.cpp:185:5: error: ‘exit’ is not a member of ‘std’
     std::exit(1);
     ^
main.cpp:185:5: note: suggested alternative:
In file included from MCMC.h:12:0,
                 from main.cpp:10:
/usr/include/stdlib.h:542:13: note:   ‘exit’
 extern void exit (int __status) __THROW __attribute__ ((__noreturn__));
             ^
make[1]: *** [main.o] Error 1
make[1]: Leaving directory`/home/enteril/Documents/Noctilio/Programs/bamm/src'
make: **\* [bamm] Error 2
